name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: Install, build, test
      run: |
        npm ci
        npm run type-check
        npm run lint
        npm run test
