name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: Install deps
    - run: |
        npm ci
        npm run type-check
        npm run lint
        npm run test
