name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: Install
    - run: npm ci
    - name: Test
    - run: npm run type-check
    - run: npm run lint
    - run: npm run test
